CAMERA_CALIBRATE_PICKLE = True
LIGHT_CALIBRATE_PICKLE = True
LIGHT_CALIBRATE_GRAPHS = True

# Light Calibrarion:
PENCIL_LENGTH_MM = 127

# Camera Calibration:
CALIB_CUBE_MM_SIZE = 20
CALIB_BOARD_SIZE = (7, 7)