CAMERA_CALIBRATE_PICKLE = True

# Global
IMG_RESIZE_FACTOR = 3

# Light Calibrarion:
PENCIL_LENGTH_MM = 127
LIGHT_CALIBRATE_PICKLE = True
LIGHT_CALIBRATE_GRAPHS = False

# Camera Calibration:
CALIB_CUBE_MM_SIZE = 20
CALIB_BOARD_SIZE = (7, 7)

# Shadow Edge Detection
INTENSITY_TRESHOLD = 40
SHADOW_POINTS_PICKLE = True
